/*
===============================================================================
SCRIPT NAME:
06_post_change_verification.sql

PURPOSE:
Confirms the new column exists with the intended definition and that the fast-default optimization was actually used.

AURORA POSTGRESQL VERSION:
Aurora PostgreSQL 17+ (compatible with community PostgreSQL 17+ unless a note says otherwise)

EXECUTION LOCATION:
Any instance (writer or reader)

SAFETY:
READ ONLY

EXPECTED IMPACT:
Minimal -- reads system catalogs/statistics views only, no table locks beyond a brief catalog lookup.

REQUIRED PRIVILEGES:
Role membership in `pg_monitor` (or `pg_read_all_stats`) is sufficient. No superuser required.

PREREQUISITES:
None beyond CONNECT on the target database.

EXECUTION ORDER:
Step 06 of workflow 'schema-changes/add-column-large-table'

RELATED SCRIPTS:
02_existing_column_inventory.sql

HOW TO INTERPRET RESULTS:
Find the new column and check three things. data_type must be exactly what you intended, including modifiers. not_null and default_expression must match the change ticket -- it is easy to end up with the default but not the constraint, or the reverse, when the steps are split. Most importantly, uses_fast_default should be true if you added the column with a constant default: that flag is the catalog's own confirmation that PostgreSQL stored the default once rather than writing it into every row, which is the difference between a millisecond change and a full rewrite. If it is false on a column you expected to be fast, the statement took the rewrite path and you should understand why before the next migration takes the same route. Edit the schema_name and table_name variables at the top for your real target.
===============================================================================
*/

-- Full column definition inventory for one target table: types, nullability,
-- defaults, identity/generated status, storage strategy, and whether a
-- previously added column is using a PostgreSQL 11+ "fast default" (stored in
-- the catalog rather than written into every existing row).
--
-- Ships with an illustrative default (public.trades); edit the \set lines
-- below for your real target. Every name here is compared only inside a
-- catalog WHERE clause and is never cast to regclass, so running this
-- unmodified against a database without that table simply returns zero rows
-- rather than failing.
\set schema_name 'public'
\set table_name 'trades'
SELECT
    a.attnum                                                     AS ordinal,
    a.attname                                                    AS column_name,
    format_type(a.atttypid, a.atttypmod)                          AS data_type,
    a.attnotnull                                                 AS not_null,
    pg_get_expr(d.adbin, d.adrelid)                               AS default_expression,
    CASE a.attidentity
         WHEN 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
         WHEN 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY'
         ELSE NULL
    END                                                          AS identity_kind,
    CASE a.attgenerated
         WHEN 's' THEN 'GENERATED ALWAYS AS ... STORED'
         ELSE NULL
    END                                                          AS generated_kind,
    CASE a.attstorage
         WHEN 'p' THEN 'plain (never TOASTed)'
         WHEN 'e' THEN 'external (TOASTed, uncompressed)'
         WHEN 'm' THEN 'main (compressed inline where possible)'
         WHEN 'x' THEN 'extended (compressed, then TOASTed)'
         ELSE a.attstorage::text
    END                                                          AS storage_strategy,
    a.atthasmissing                                              AS uses_fast_default,
    col_description(a.attrelid, a.attnum)                         AS column_comment
FROM pg_attribute a
JOIN pg_class c ON c.oid = a.attrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE n.nspname = :'schema_name'
  AND c.relname = :'table_name'
  AND a.attnum > 0
  AND NOT a.attisdropped
ORDER BY a.attnum;
