/*
===============================================================================
SCRIPT NAME:
01_column_definition_inventory.sql

PURPOSE:
Reads the exact current definition of every column on the target table, including type modifiers, defaults, and identity status.

AURORA POSTGRESQL VERSION:
Aurora PostgreSQL 17+ (compatible with community PostgreSQL 17+ unless a note says otherwise)

EXECUTION LOCATION:
Any instance (writer or reader)

SAFETY:
READ ONLY

EXPECTED IMPACT:
Minimal -- reads system catalogs/statistics views only, no table locks beyond a brief catalog lookup.

REQUIRED PRIVILEGES:
Role membership in `pg_monitor` (or `pg_read_all_stats`) is sufficient. No superuser required.

PREREQUISITES:
None beyond CONNECT on the target database.

EXECUTION ORDER:
Step 01 of workflow 'schema-changes/column-type-change'

RELATED SCRIPTS:
02_dependent_objects_inventory.sql

HOW TO INTERPRET RESULTS:
Read data_type exactly as reported, including the modifiers -- the difference between numeric(18,8) and numeric(20,8) determines whether the change is instant or a full rewrite, and a description like 'the amount column' is not precise enough to classify. Check identity_kind and generated_kind: an identity column is backed by a sequence that may itself be near its ceiling, and a stored generated column has its own rewrite rules. storage_strategy matters for wide columns, since changing a type can change how values are TOASTed. Edit the schema_name and table_name variables at the top for your real target; names are compared only inside a WHERE clause here, so an absent table returns zero rows rather than failing.
===============================================================================
*/

-- Full column definition inventory for one target table: types, nullability,
-- defaults, identity/generated status, storage strategy, and whether a
-- previously added column is using a PostgreSQL 11+ "fast default" (stored in
-- the catalog rather than written into every existing row).
--
-- Ships with an illustrative default (public.trades); edit the \set lines
-- below for your real target. Every name here is compared only inside a
-- catalog WHERE clause and is never cast to regclass, so running this
-- unmodified against a database without that table simply returns zero rows
-- rather than failing.
\set schema_name 'public'
\set table_name 'trades'
SELECT
    a.attnum                                                     AS ordinal,
    a.attname                                                    AS column_name,
    format_type(a.atttypid, a.atttypmod)                          AS data_type,
    a.attnotnull                                                 AS not_null,
    pg_get_expr(d.adbin, d.adrelid)                               AS default_expression,
    CASE a.attidentity
         WHEN 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
         WHEN 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY'
         ELSE NULL
    END                                                          AS identity_kind,
    CASE a.attgenerated
         WHEN 's' THEN 'GENERATED ALWAYS AS ... STORED'
         ELSE NULL
    END                                                          AS generated_kind,
    CASE a.attstorage
         WHEN 'p' THEN 'plain (never TOASTed)'
         WHEN 'e' THEN 'external (TOASTed, uncompressed)'
         WHEN 'm' THEN 'main (compressed inline where possible)'
         WHEN 'x' THEN 'extended (compressed, then TOASTed)'
         ELSE a.attstorage::text
    END                                                          AS storage_strategy,
    a.atthasmissing                                              AS uses_fast_default,
    col_description(a.attrelid, a.attnum)                         AS column_comment
FROM pg_attribute a
JOIN pg_class c ON c.oid = a.attrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE n.nspname = :'schema_name'
  AND c.relname = :'table_name'
  AND a.attnum > 0
  AND NOT a.attisdropped
ORDER BY a.attnum;
