/*
===============================================================================
SCRIPT NAME:
06_post_change_verification.sql

PURPOSE:
Confirms the column now has the intended type and that no index or constraint was left invalid by the change.

AURORA POSTGRESQL VERSION:
Aurora PostgreSQL 17+ (compatible with community PostgreSQL 17+ unless a note says otherwise)

EXECUTION LOCATION:
Any instance (writer or reader)

SAFETY:
READ ONLY

EXPECTED IMPACT:
Minimal -- reads system catalogs/statistics views only, no table locks beyond a brief catalog lookup.

REQUIRED PRIVILEGES:
Role membership in `pg_monitor` (or `pg_read_all_stats`) is sufficient. No superuser required.

PREREQUISITES:
None beyond CONNECT on the target database.

EXECUTION ORDER:
Step 06 of workflow 'schema-changes/column-type-change'

RELATED SCRIPTS:
02_dependent_objects_inventory.sql

HOW TO INTERPRET RESULTS:
Check data_type on the changed column reports exactly the type and modifiers you intended, including precision and scale -- a financial column that ended up with the wrong scale is a silent correctness failure that reconciliation will find later and far more expensively. Confirm not_null and default_expression survived the change, since both are easy to lose in an add-and-swap. The second result set must contain no index on this table: an INVALID index here means the concurrent build in step 4 of the runbook did not complete, and the table is now missing an index the planner needs. Finally, re-run the dependent objects inventory and confirm every view still resolves and every constraint is still validated.
===============================================================================
*/

-- Full column definition inventory for one target table: types, nullability,
-- defaults, identity/generated status, storage strategy, and whether a
-- previously added column is using a PostgreSQL 11+ "fast default" (stored in
-- the catalog rather than written into every existing row).
--
-- Ships with an illustrative default (public.trades); edit the \set lines
-- below for your real target. Every name here is compared only inside a
-- catalog WHERE clause and is never cast to regclass, so running this
-- unmodified against a database without that table simply returns zero rows
-- rather than failing.
\set schema_name 'public'
\set table_name 'trades'
SELECT
    a.attnum                                                     AS ordinal,
    a.attname                                                    AS column_name,
    format_type(a.atttypid, a.atttypmod)                          AS data_type,
    a.attnotnull                                                 AS not_null,
    pg_get_expr(d.adbin, d.adrelid)                               AS default_expression,
    CASE a.attidentity
         WHEN 'a' THEN 'GENERATED ALWAYS AS IDENTITY'
         WHEN 'd' THEN 'GENERATED BY DEFAULT AS IDENTITY'
         ELSE NULL
    END                                                          AS identity_kind,
    CASE a.attgenerated
         WHEN 's' THEN 'GENERATED ALWAYS AS ... STORED'
         ELSE NULL
    END                                                          AS generated_kind,
    CASE a.attstorage
         WHEN 'p' THEN 'plain (never TOASTed)'
         WHEN 'e' THEN 'external (TOASTed, uncompressed)'
         WHEN 'm' THEN 'main (compressed inline where possible)'
         WHEN 'x' THEN 'extended (compressed, then TOASTed)'
         ELSE a.attstorage::text
    END                                                          AS storage_strategy,
    a.atthasmissing                                              AS uses_fast_default,
    col_description(a.attrelid, a.attnum)                         AS column_comment
FROM pg_attribute a
JOIN pg_class c ON c.oid = a.attrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
WHERE n.nspname = :'schema_name'
  AND c.relname = :'table_name'
  AND a.attnum > 0
  AND NOT a.attisdropped
ORDER BY a.attnum;

-- Indexes left in an INVALID state, almost always because a previous
-- CREATE INDEX CONCURRENTLY or REINDEX CONCURRENTLY failed partway through
-- (a killed session, statement_timeout, or deadlock). Invalid indexes are
-- not used by the planner but still consume storage and slow down writes,
-- so they should be dropped and, if needed, recreated concurrently.
SELECT
    n.nspname                                                   AS schema_name,
    c.relname                                                   AS table_name,
    i.relname                                                   AS index_name,
    pg_size_pretty(pg_relation_size(i.oid))                      AS wasted_size,
    pg_get_indexdef(ix.indexrelid)                               AS index_definition
FROM pg_index ix
JOIN pg_class c ON c.oid = ix.indrelid
JOIN pg_class i ON i.oid = ix.indexrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE NOT ix.indisvalid
ORDER BY pg_relation_size(i.oid) DESC;
